name: crystal-microservice-example
version: "1.10"
summary: An example of a microservice written on Crystal and Lucky framework
description: |
  HTTP-based microservice, written on Crystal, to compare programming languages in real tasks.

grade: devel
confinement: strict

apps:
  crystal-microservice-example:
    command: start_server
    plugs:
      - network

parts:
  crystal-microservice-example:
    plugin: crystal
