# This is the default error serializer generated by Lucky.
# Feel free to customize it in any way you like.
class Errors::ShowSerializer < Lucky::Serializer
  def initialize(@message : String, @code : Int32, @details : String? = nil)
  end

  def render
    {status: @code, error: @message, details: @details}
  end
end
